#!/bin/sh

if test "$UID" = "0"; then
	# running as root anyway, don't need sudo
	INSMOD="/sbin/insmod"
	RMMOD="/sbin/rmmod"
else
	INSMOD="sudo /sbin/insmod"
	RMMOD="sudo /sbin/rmmod"
fi

# handy functions for rmmod/insmod
function xrmmod () {
	grep -qe "^$1" /proc/modules || return
	echo rmmod $1
	$RMMOD $1 || exit 1
}
function xinsmod () {
	echo insmod $*
	$INSMOD -f $* || exit 1
}

# prepare for crashing the box -- flush dirty buffers
sync; sleep 1; sync

# kill old modules ...
xrmmod tuner
xrmmod i2c-dev
xrmmod bttv
xrmmod algo-bit
xrmmod i2c
xrmmod videodev

# ... and load the new ones
xinsmod videodev
xinsmod i2c.o
xinsmod algo-bit.o	test=1 scan=0
xinsmod tuner		debug=1 type=5 
xinsmod bttv		radio=1 vidmem=0xff0

